# Generated by Django 3.2 on 2023-09-07 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolDetail',
        ),
    ]
