# Generated by Django 3.2 on 2023-09-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('teacher', 'teacher'), ('student', 'student'), ('parent', 'parent'), ('admin', 'admin'), ('inactive', 'inactive')], default='inactive', max_length=15),
        ),
    ]
