# Generated by Django 3.2 on 2023-07-27 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_classgroup'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='class_group',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='curriculum.classgroup'),
        ),
        migrations.DeleteModel(
            name='ClassGroup',
        ),
    ]
