# Generated by Django 3.2 on 2023-09-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='date_admitted',
            field=models.DateField(verbose_name='Admission date (MM-DD-YYYY)'),
        ),
    ]
