# Generated by Django 3.2 on 2023-08-17 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_classgroup'),
        ('students', '0003_alter_studentdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.classgroup'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='current_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.standard'),
        ),
    ]
