# Generated by Django 3.2 on 2023-08-17 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20230817_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.badge'),
        ),
    ]
