# Generated by Django 3.2 on 2023-08-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_studentdetail_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='date_admitted',
            field=models.DateField(verbose_name='Admission date (YYYY-MM-DD)'),
        ),
    ]
