# Generated by Django 3.2 on 2023-07-27 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('term', models.CharField(blank=True, choices=[('first_term', 'first_term'), ('second_term', 'second_term'), ('third_term', 'third_term'), ('others', 'others')], max_length=50)),
                ('amount_due', models.CharField(blank=True, max_length=150)),
                ('payment_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.paymentcategory')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.session')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'cash'), ('bank_deposit', 'bank_deposit'), ('cheque', 'cheque'), ('pos', 'pos')], max_length=50)),
                ('depositor', models.CharField(max_length=150)),
                ('bank_name', models.CharField(max_length=150)),
                ('teller', models.CharField(blank=True, max_length=150)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(blank=True, upload_to='payments', verbose_name='upload receipt')),
                ('confirmed', models.BooleanField(default=False)),
                ('payment_recorded_date', models.DateField(auto_now_add=True)),
                ('payment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.paymentchart')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentdetail')),
            ],
        ),
    ]
