# Generated by Django 3.2 on 2023-07-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcategory',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
