# Generated by Django 3.2 on 2023-09-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcategory',
            name='name',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
