# Generated by Django 3.2 on 2023-09-24 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_paymentcategory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('acc_number', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='bank_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.bankdetail'),
        ),
    ]
