# Generated by Django 3.2 on 2023-07-31 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20230731_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='amount_paid',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(2, 'at least 3digits required')]),
        ),
    ]
