# Generated by Django 3.2 on 2023-07-31 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_paymentdetail_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='amount_paid',
            field=models.IntegerField(),
        ),
    ]
