# Generated by Django 3.2 on 2023-08-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_paymentdetail_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentchart',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
