# Generated by Django 3.2 on 2023-09-02 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_studentdetail_date_admitted'),
        ('payment', '0007_alter_paymentdetail_amount_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='file',
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='installment_level',
            field=models.CharField(choices=[('First_payment', 'First_payment'), ('Second_payment', 'Second_payment'), ('Third_payment', 'Third_payment'), ('Fourth_payment', 'Fourth_payment')], default='select_installment', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='student_detail',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentdetail'),
        ),
        migrations.AlterField(
            model_name='paymentchart',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
