# Generated by Django 3.2 on 2023-09-01 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_paymentchart_amount_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='file',
        ),
    ]
