# Generated by Django 3.2 on 2023-09-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_alter_paymentdetail_installment_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'cash'), ('bank_deposit', 'bank_deposit'), ('bank_transfer', 'bank_transfer'), ('cheque', 'cheque'), ('pos', 'pos')], max_length=50),
        ),
    ]
