# Generated by Django 3.2 on 2023-07-28 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staffprofile_class_group'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitems',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventoryitems',
            name='date_recorded',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='inventoryitems',
            name='item_location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='inventoryitems',
            name='staff_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staffprofile'),
        ),
    ]
