# Generated by Django 3.2 on 2023-09-07 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_schooldetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolDetail',
        ),
    ]
