# Generated by Django 3.2 on 2023-09-18 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_term'),
        ('attendance', '0002_auto_20230917_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(blank=True, default='2023/2024', null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.session'),
        ),
    ]
